apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: express-sample-app
    - name: image-repo
      value: quay.io/ophelia_huang/ophelia-kat-express
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/ophelia-katarina-assignment.git
  pipelineRef:
    name: buildah
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce 
        resources:
          requests:
            storage: 1Gi