apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/ophelia_huang/ophelia-kat-express
  newTag: 0a9915105dab249d41c49d95e58a1c6ba1136cf3f1dfbcb5889bed818cee936f
commonLabels:
  app.kubernetes.io/instance: express-sample-app
  app.kubernetes.io/name: express-sample-app
