apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
- webhook-receiver.EventListener.yaml
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/kcimesa/express-sample-app
  newTag: 3d186919cd1579669d0985fd7ef3377ed50b4052
commonLabels:
  app.kubernetes.io/instance: express-sample-app
  app.kubernetes.io/name: express-sample-app
