apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJhMk5wYldWellTdGlkV2xzWkdGb1gzQnBjR1ZzYVc1bE9rRkJOVEJQVkZwRE5UTlFRMHd4TXpGUk9GUkJSMVZPTlZCRk9UY3pTbGhQVWtSUFZ6UXhNVE5hVmtJd05rcEhNak5MVGxCVVJWUlRVakZRVFUxUk1rST0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson